./a.out < upable/cases/case_0.in > upable/cases/case_0.out
./a.out < upable/cases/case_1.in > upable/cases/case_1.out
./a.out < upable/cases/case_2.in > upable/cases/case_2.out
./a.out < upable/cases/case_3.in > upable/cases/case_3.out
./a.out < upable/cases/case_4.in > upable/cases/case_4.out
./a.out < upable/cases/case_5.in > upable/cases/case_5.out
./a.out < upable/cases/case_6.in > upable/cases/case_6.out
./a.out < upable/cases/case_7.in > upable/cases/case_7.out
./a.out < upable/cases/case_8.in > upable/cases/case_8.out
./a.out < upable/cases/case_9.in > upable/cases/case_9.out
./a.out < upable/cases/case_10.in > upable/cases/case_10.out
./a.out < upable/cases/case_11.in > upable/cases/case_11.out
./a.out < upable/cases/case_12.in > upable/cases/case_12.out
./a.out < upable/cases/case_13.in > upable/cases/case_13.out
./a.out < upable/cases/case_14.in > upable/cases/case_14.out
./a.out < upable/cases/case_15.in > upable/cases/case_15.out
./a.out < upable/cases/case_16.in > upable/cases/case_16.out
./a.out < upable/cases/case_17.in > upable/cases/case_17.out
./a.out < upable/cases/case_18.in > upable/cases/case_18.out
./a.out < upable/cases/case_19.in > upable/cases/case_19.out
